/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fonsterandrauppgifter;

import fonsterandrauppgifter.Services.AnstalldService;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author anton
 */
public class MinaUppgifter extends javax.swing.JFrame {
    
    private InfDB idb;
    private String anstalldAid; 

    /**
     * Creates new form MinaUppgifter
     */
    public MinaUppgifter(InfDB idb, String anstalldAid) {
        this.idb = idb; 
        this.anstalldAid = anstalldAid; 
        initComponents();
        hamtaUppgifter(); 
        
    }
    
    public void hamtaUppgifter(){
 
        try{
             String sqlFnamn = "SELECT fornamn FROM anstalld WHERE aid =" + anstalldAid;
             String sqlEnamn = "SELECT efternamn FROM anstalld WHERE aid =" + anstalldAid;
             String sqlAdress = "SELECT adress FROM anstalld WHERE aid =" + anstalldAid;
             String sqlEpost = "SELECT epost FROM anstalld WHERE aid =" + anstalldAid;
             String sqlTele = "SELECT telefon FROM anstalld WHERE aid =" + anstalldAid;
             String sqlAnsDatum = "SELECT anstallningsdatum FROM anstalld WHERE aid =" + anstalldAid;
             String sqlAvd = "SELECT avdelning FROM anstalld WHERE aid =" + anstalldAid;
             String dbFnamn = idb.fetchSingle(sqlFnamn);
             String dbEnamn = idb.fetchSingle(sqlEnamn);
             String dbAdress = idb.fetchSingle(sqlAdress);
             String dbEpost = idb.fetchSingle(sqlEpost);
             String dbTele = idb.fetchSingle(sqlTele);
             String dbAnsDatum = idb.fetchSingle(sqlAnsDatum);
             String dbAvd = idb.fetchSingle(sqlAvd);
             lblSQLFnamn.setText(dbFnamn);
             lblSQLEnamn.setText(dbEnamn);
             lblSQLAdress.setText(dbAdress);
             lblSQLEpost.setText(dbEpost);
             lblSQLTele.setText(dbTele);
             lblSQLAnsDatum.setText(dbAnsDatum);
             lblSQLAvd.setText(dbAvd);
             
        }catch(InfException ettUndantagsFel){
            System.out.println(ettUndantagsFel.getMessage());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMinaUppgifter = new javax.swing.JLabel();
        lblFnamn = new javax.swing.JLabel();
        lblEnamn = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTele = new javax.swing.JLabel();
        lblAnsDatum = new javax.swing.JLabel();
        lblAvd = new javax.swing.JLabel();
        lblSQLFnamn = new javax.swing.JLabel();
        lblSQLEnamn = new javax.swing.JLabel();
        lblSQLAdress = new javax.swing.JLabel();
        lblSQLEpost = new javax.swing.JLabel();
        lblSQLTele = new javax.swing.JLabel();
        lblSQLAnsDatum = new javax.swing.JLabel();
        lblSQLAvd = new javax.swing.JLabel();
        btnAndraUppgifter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMinaUppgifter.setText("Mina uppgifter");

        lblFnamn.setText("Förnamn");

        lblEnamn.setText("Efternamn");

        lblAdress.setText("Adress");

        lblEpost.setText("Epost");

        lblTele.setText("Telefon");

        lblAnsDatum.setText("Anställningsdatum");

        lblAvd.setText("Avdelning");

        lblSQLFnamn.setText("jLabel1");

        lblSQLEnamn.setText("jLabel1");

        lblSQLAdress.setText("jLabel2");

        lblSQLEpost.setText("jLabel3");

        lblSQLTele.setText("jLabel4");

        lblSQLAnsDatum.setText("jLabel5");

        lblSQLAvd.setText("jLabel6");

        btnAndraUppgifter.setText("Ändra uppgifter");
        btnAndraUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraUppgifterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblMinaUppgifter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnamn)
                            .addComponent(lblFnamn)
                            .addComponent(lblAvd)
                            .addComponent(lblAnsDatum)
                            .addComponent(lblTele)
                            .addComponent(lblAdress)
                            .addComponent(lblEpost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSQLFnamn)
                            .addComponent(lblSQLEnamn)
                            .addComponent(lblSQLAdress)
                            .addComponent(lblSQLEpost)
                            .addComponent(lblSQLTele)
                            .addComponent(lblSQLAnsDatum)
                            .addComponent(lblSQLAvd)
                            .addComponent(btnAndraUppgifter))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMinaUppgifter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFnamn)
                    .addComponent(lblSQLFnamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnamn)
                    .addComponent(lblSQLEnamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(lblSQLAdress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(lblSQLEpost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTele)
                    .addComponent(lblSQLTele))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsDatum)
                    .addComponent(lblSQLAnsDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvd)
                    .addComponent(lblSQLAvd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnAndraUppgifter)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraUppgifterActionPerformed
        AnstalldService anstalldService = new AnstalldService(idb, anstalldAid); 
        new AndraUppgifter(idb, anstalldAid, anstalldService).setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnAndraUppgifterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MinaUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraUppgifter;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAnsDatum;
    private javax.swing.JLabel lblAvd;
    private javax.swing.JLabel lblEnamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFnamn;
    private javax.swing.JLabel lblMinaUppgifter;
    private javax.swing.JLabel lblSQLAdress;
    private javax.swing.JLabel lblSQLAnsDatum;
    private javax.swing.JLabel lblSQLAvd;
    private javax.swing.JLabel lblSQLEnamn;
    private javax.swing.JLabel lblSQLEpost;
    private javax.swing.JLabel lblSQLFnamn;
    private javax.swing.JLabel lblSQLTele;
    private javax.swing.JLabel lblTele;
    // End of variables declaration//GEN-END:variables
}
